// vue-client/src/ToDoList.vue
<script setup>
import { onMounted, ref } from 'vue';

const todos = ref([])
onMounted(() => {
    fetch('http://localhost:3000/api/todos')
        .then(response => response.json())
        .then(data => {
            todos.value = data
        })
})
</script>

<template>
    <h2>List</h2>
    <button @click="$router.push('/add')">Add</button>
    <ul>
        <li v-for="todo in todos" :key="todo.id" :style="{ textDecoration: todo.completed ? 'line-through' : 'none' }">
            {{ todo.title }}
        </li>
    </ul>
</template>

// svelte-client/src/TodoList.svelte
<script>
  import { router } from './router';
  import { onMount } from 'svelte';
  const state = $state({ todos: [] });
  onMount(() => {
    fetch('http://localhost:3000/api/todos')
      .then(res => res.json())
      .then(data => {
        state.todos = data;
      });   
  });
</script>

<h2>Todo List</h2>
<button onclick={() => router.navigate('/add')}>Add</button>
<ul>
  {#each state.todos as todo}
    <li style:text-decoration={todo.completed ? 'line-through' : 'none'}>
      {todo.title}
    </li>
  {/each}
</ul>
