// react-client/src/components/ToDoList.jsx
import { useEffect, useState } from "react"
import { useNavigate } from "react-router-dom"

export default function ToDoList() {
    const [todos, setTodos] = useState([])
    useEffect(() => {
        fetch('http://localhost:3000/api/todos')
            .then(res => res.json())
            .then(setTodos)
    }, [])
    const navigate = useNavigate()
    const handleAdd = () => {
        navigate('/add')
    }
  return <>
    <h2>List</h2>
    <button onClick={handleAdd}>Add</button>
    <ul>
        {todos.map(todo => <li 
            key={todo.id}
            style={{textDecoration: todo.completed ? 'line-through' : ''}}
            >
                {todo.title}
            </li>)
        }
    </ul>
  </>
}

// vue-client/src/ToDoList.vue
<script setup>
import { onMounted, ref } from 'vue';

const todos = ref([])
onMounted(() => {
    fetch('http://localhost:3000/api/todos')
        .then(response => response.json())
        .then(data => {
            todos.value = data
        })
})
</script>

<template>
    <h2>List</h2>
    <button @click="$router.push('/add')">Add</button>
    <ul>
        <li v-for="todo in todos" :key="todo.id" :style="{ textDecoration: todo.completed ? 'line-through' : 'none' }">
            {{ todo.title }}
        </li>
    </ul>
</template>
